In [1]:
#pandas library used to data cleaning ,data manipulation,data processing
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: pandas in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: pandas in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd

In [3]:
#pandas two data formats
#1 series - 1D column
#2 DataFrame - 2D data(columns and rows)

In [12]:
#series
a=[1,2,3,4,5]
n=pd.Series(a)
print(n)
print(type(n))
print(n.dtype)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
int64

In [19]:
b=pd.Series([2.0,4.0,4.4,6.9])
print(b)
print(type(b))
print(b.dtype)
print(b.index)
print(b.values)

0    2.0
1    4.0
2    4.4
3    6.9
dtype: float64
<class 'pandas.core.series.Series'>
float64
RangeIndex(start=0, stop=4, step=1)
[2.  4.  4.4 6.9]

In [5]:
import pandas as pd
b=pd.Series([2.0,4.0,4.4,6.9],index=['a','b','c','d'])
print(b)
print(b.index)
print(b.values)

a    2.0
b    4.0
c    4.4
d    6.9
dtype: float64
Index(['a', 'b', 'c', 'd'], dtype='object')
[2.  4.  4.4 6.9]

In [26]:
#creating series with array data
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: numpy in /opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages (1.24.3)

In [30]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
n=pd.Series(a)
print(n)
print(type(n))
c=np.array(n)
print(c)

[1 2 3 4 5]
<class 'numpy.ndarray'>
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1 2 3 4 5]

In [37]:
#filtering of data using single and multiple conditions
n=pd.Series([3,6,88,99,77,85,77,66,80,66])
print(n>60)
print(n[n>60])
print(n[n!=3])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
dtype: bool
2    88
3    99
4    77
5    85
6    77
7    66
8    80
9    66
dtype: int64
1     6
2    88
3    99
4    77
5    85
6    77
7    66
8    80
9    66
dtype: int64

In [51]:
#multiple conditions
#and & or operators|
n=pd.Series([3,6,88,99,77,85,77,66,80,66])
print((n>2)&(n<20))
print(n[(n>2)&(n<55)])
print(n[(n>2)|(n<55)])

0     True
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool
0    3
1    6
dtype: int64
0     3
1     6
2    88
3    99
4    77
5    85
6    77
7    66
8    80
9    66
dtype: int64

In [58]:
x=pd.Series([1,2,3,4,5])
print(x)
x[1]=200
print(x)
x[3:]=400,500
print(x)
x[0:3:2]=400,5
print(x)
#change 200 and 500 to 7.4 and 3.8
x[0:3:2]=7.4,3.8
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0      1
1    200
2      3
3      4
4      5
dtype: int64
0      1
1    200
2      3
3    400
4    500
dtype: int64
0    400
1    200
2      5
3    400
4    500
dtype: int64
0      7.4
1    200.0
2      3.8
3    400.0
4    500.0
dtype: float64

In [1]:
#data pre-processing
#checking for unique values
n=pd.Series([3,6,88,99,77,85,77,66,80,66])
print(n.unique())

#value counts--prints the count for unique values
print(n.value_counts())

NameError: name 'pd' is not defined

In [74]:
#data cleaning process
#null values
n=pd.Series([1,np.nan,2,4,6,np.nan,7,8,9,np.nan,5])
print(n)
print(n.value_counts())
print(n.isnull().sum())
print(n.isna().sum())

0     1.0
1     NaN
2     2.0
3     4.0
4     6.0
5     NaN
6     7.0
7     8.0
8     9.0
9     NaN
10    5.0
dtype: float64
1.0    1
2.0    1
4.0    1
6.0    1
7.0    1
8.0    1
9.0    1
5.0    1
Name: count, dtype: int64
3
3

In [75]:
#filling null values
#fillna(),bfill(),ffill(),mean(),median(),mode()
#fillna()
print(n.fillna(5))

0     1.0
1     5.0
2     2.0
3     4.0
4     6.0
5     5.0
6     7.0
7     8.0
8     9.0
9     5.0
10    5.0
dtype: float64

In [76]:
#bfill()- backward fill
print(n.bfill())
print(n.isnull().sum())

0     1.0
1     2.0
2     2.0
3     4.0
4     6.0
5     7.0
6     7.0
7     8.0
8     9.0
9     5.0
10    5.0
dtype: float64
3

In [77]:
#ffill()
print(n.ffill())

0     1.0
1     1.0
2     2.0
3     4.0
4     6.0
5     6.0
6     7.0
7     8.0
8     9.0
9     9.0
10    5.0
dtype: float64

In [79]:
#mean()
x=n.mean()
print(x)
print(n.fillna(x))

5.25
0     1.00
1     5.25
2     2.00
3     4.00
4     6.00
5     5.25
6     7.00
7     8.00
8     9.00
9     5.25
10    5.00
dtype: float64

In [83]:
y=n.mode()
print(y)
print(n.fillna(y))

0    1.0
1    2.0
2    4.0
3    5.0
4    6.0
5    7.0
6    8.0
7    9.0
dtype: float64
0     1.0
1     2.0
2     2.0
3     4.0
4     6.0
5     7.0
6     7.0
7     8.0
8     9.0
9     NaN
10    5.0
dtype: float64

In [85]:
z=n.median()
print(z)
print(n.fillna(z))

5.5
0     1.0
1     5.5
2     2.0
3     4.0
4     6.0
5     5.5
6     7.0
7     8.0
8     9.0
9     5.5
10    5.0
dtype: float64

In [89]:
m=pd.Series([1,np.nan,2,4,6,np.nan,7,8,9,np.nan,5])
p=m.mode()
print(p)
print(m.fillna(p[1]))

0    1.0
1    2.0
2    4.0
3    5.0
4    6.0
5    7.0
6    8.0
7    9.0
dtype: float64
0     1.0
1     2.0
2     2.0
3     4.0
4     6.0
5     2.0
6     7.0
7     8.0
8     9.0
9     2.0
10    5.0
dtype: float64

In [15]:
#task 1
import pandas as pd
a=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(a)
print(a['c'])
print(a['b':'d'])
print(a[::4])

a    10
b    20
c    30
d    40
e    50
dtype: int64
30
b    20
c    30
d    40
dtype: int64
a    10
e    50
dtype: int64

In [2]:
#task 2
import numpy as np
import pandas as pd
a=np.array([5,15,25,35,45])
print(a)
print(type(a))
b=pd.Series(a)
print(b)
print(type(b))
c=np.array(b)
print(c)

[ 5 15 25 35 45]
<class 'numpy.ndarray'>
0     5
1    15
2    25
3    35
4    45
dtype: int64
<class 'pandas.core.series.Series'>
[ 5 15 25 35 45]

In [33]:
#task 3
a=pd.Series([12,45,67,23,89,34,10,5])
print(a[a>30])
print(a[(a>=20)&(a<=70)])
print(a[(a<15)|(a>80)])

1    45
2    67
4    89
5    34
dtype: int64
1    45
2    67
3    23
5    34
dtype: int64
0    12
4    89
6    10
7     5
dtype: int64

In [37]:
#task 4
a=[1,2,3,4,5]
a[1]=100
print(a)
a[3:5]=200,300
print(a)
a[0:3:2]=50,60
print(a)

[1, 100, 3, 4, 5]
[1, 100, 3, 200, 300]
[50, 100, 60, 200, 300]

In [49]:
#task 5
a=pd.Series([2,5,np.nan,7,2,np.nan,8,2,9])
print(a)
print(a.unique())
print(a.value_counts())
print(a.isnull().sum())
b=a.mean()
print(a.fillna(b))
print(a.ffill())
print(a.bfill())
c=a.mode()
print(a.fillna(c))

0    2.0
1    5.0
2    NaN
3    7.0
4    2.0
5    NaN
6    8.0
7    2.0
8    9.0
dtype: float64
[ 2.  5. nan  7.  8.  9.]
2.0    3
5.0    1
7.0    1
8.0    1
9.0    1
Name: count, dtype: int64
2
0    2.0
1    5.0
2    5.0
3    7.0
4    2.0
5    5.0
6    8.0
7    2.0
8    9.0
dtype: float64
0    2.0
1    5.0
2    5.0
3    7.0
4    2.0
5    2.0
6    8.0
7    2.0
8    9.0
dtype: float64
0    2.0
1    5.0
2    7.0
3    7.0
4    2.0
5    8.0
6    8.0
7    2.0
8    9.0
dtype: float64
0    2.0
1    5.0
2    NaN
3    7.0
4    2.0
5    NaN
6    8.0
7    2.0
8    9.0
dtype: float64

In [13]:
#task 6
a=pd.Series([78,56,89,45,67,90,34,88,76,54,93,48,60,73,85],
                index=['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14', 's15'
                      ])
print(a[a>80])
print(a[(a>=50)&(a<=75)])
b=a[a<50]
print(b)
print(b.value_counts().sum())
a[a<50]+=5
print(a)
a[a>=90]=95
print(a)

s3     89
s6     90
s8     88
s11    93
s15    85
dtype: int64
s2     56
s5     67
s10    54
s13    60
s14    73
dtype: int64
s4     45
s7     34
s12    48
dtype: int64
3
s1     78
s2     56
s3     89
s4     50
s5     67
s6     90
s7     39
s8     88
s9     76
s10    54
s11    93
s12    53
s13    60
s14    73
s15    85
dtype: int64
s1     78
s2     56
s3     89
s4     50
s5     67
s6     95
s7     39
s8     88
s9     76
s10    54
s11    95
s12    53
s13    60
s14    73
s15    85
dtype: int64

In [32]:
#task 7
temps=[32,35,np.nan,40,38,np.nan,36,37,np.nan,39,41,np.nan]
a=pd.Series(temps)
print(a)
print(a.isnull().sum())
x=a.mean()
print(x)
print(a.fillna(x))
print(a.ffill())
print(a.bfill())
print(a[a>38])
a[a<=33]=33
print(a)

0     32.0
1     35.0
2      NaN
3     40.0
4     38.0
5      NaN
6     36.0
7     37.0
8      NaN
9     39.0
10    41.0
11     NaN
dtype: float64
4
37.25
0     32.00
1     35.00
2     37.25
3     40.00
4     38.00
5     37.25
6     36.00
7     37.00
8     37.25
9     39.00
10    41.00
11    37.25
dtype: float64
0     32.0
1     35.0
2     35.0
3     40.0
4     38.0
5     38.0
6     36.0
7     37.0
8     37.0
9     39.0
10    41.0
11    41.0
dtype: float64
0     32.0
1     35.0
2     40.0
3     40.0
4     38.0
5     36.0
6     36.0
7     37.0
8     39.0
9     39.0
10    41.0
11     NaN
dtype: float64
3     40.0
9     39.0
10    41.0
dtype: float64
0     33.0
1     35.0
2      NaN
3     40.0
4     38.0
5      NaN
6     36.0
7     37.0
8      NaN
9     39.0
10    41.0
11     NaN
dtype: float64

In [23]:
#drop the null values
#dropna()
m=pd.Series([1,np.nan,2,4,6,np.nan,7,8,9,np.nan,5])
print(m.dropna())
#inplace =true-parameter used to fix the drop or fill in original data
m.dropna(inplace=True)
print(m)

0     1.0
2     2.0
3     4.0
4     6.0
6     7.0
7     8.0
8     9.0
10    5.0
dtype: float64
0     1.0
2     2.0
3     4.0
4     6.0
6     7.0
7     8.0
8     9.0
10    5.0
dtype: float64

In [76]:
#data frame-2d data of rows and columns - example excel sheet
dict={"state":["karnataka","maharastra","goa","kerala"],
      "year":[2022,2024,2025,2026],
      "pop":[1.7,2.4,5.5,6.6]
     }
print(dict)
df=pd.DataFrame(dict)
print(df)

{'state': ['karnataka', 'maharastra', 'goa', 'kerala'], 'year': [2022, 2024, 2025, 2026], 'pop': [1.7, 2.4, 5.5, 6.6]}
        state  year  pop
0   karnataka  2022  1.7
1  maharastra  2024  2.4
2         goa  2025  5.5
3      kerala  2026  6.6

In [77]:
df1=pd.DataFrame(dict,index=[10,20,30,40])
df1

         state  year  pop
10   karnataka  2022  1.7
20  maharastra  2024  2.4
30         goa  2025  5.5
40      kerala  2026  6.6

In [90]:
#accessing columns from data frame
print(df[["state","pop"]])

print(df["state"][0])

        state  pop
0   karnataka  1.7
1  maharastra  2.4
2         goa  5.5
3      kerala  6.6
karnataka

In [110]:
#accessing rows
#iloc- works with only default index value
#loc-works with default index and user defined index
print(df.iloc[0,0])
print(df.iloc[2,1])
print(df.iloc[0:2,0:2])
print(df.iloc[0:2,:])
print(df.iloc[[0,1,3],:])

karnataka
2025
        state  year
0   karnataka  2022
1  maharastra  2024
        state  year  pop
0   karnataka  2022  1.7
1  maharastra  2024  2.4
        state  year  pop
0   karnataka  2022  1.7
1  maharastra  2024  2.4
3      kerala  2026  6.6

In [118]:
#loc
print(df)
print(df.loc[0,"year"])
print(df.loc[1:,"year"])
print(df.loc[1:,"pop"])

        state  year  pop
0   karnataka  2022  1.7
1  maharastra  2024  2.4
2         goa  2025  5.5
3      kerala  2026  6.6
2022
1    2024
2    2025
3    2026
Name: year, dtype: int64
1    2.4
2    5.5
3    6.6
Name: pop, dtype: float64

In [153]:
#create dataframe using dictionary with following columns
#empid,name,gender,designation,salary-6 values
data={"empid":[22,44,55,56,77,89],
      "name":["mugni","farzeen","gavin","nasir","shahim","moosa"],
      "gender":["g","m","m","m","m","m"],
      "designation":["worker","manager","waiter","boss","watchman","ceo"],
      "salary":[50,88,88,99,99,99]}
print(data)
df=pd.DataFrame(data)
print(df)
df1=pd.DataFrame(data,index=[1,2,3,4,5,6])
df1
print(df1)
print(df[df["salary"]==50])
print(df[df["salary"]<80])
#multiple condition
print(df[(df["gender"]=="m")&(df["salary"]>80)])
print(df[(df["gender"]=="g")|(df["designation"]=="worker")])
print(df[(df["name"]=="mugni")])

{'empid': [22, 44, 55, 56, 77, 89], 'name': ['mugni', 'farzeen', 'gavin', 'nasir', 'shahim', 'moosa'], 'gender': ['g', 'm', 'm', 'm', 'm', 'm'], 'designation': ['worker', 'manager', 'waiter', 'boss', 'watchman', 'ceo'], 'salary': [50, 88, 88, 99, 99, 99]}
   empid     name gender designation  salary
0     22    mugni      g      worker      50
1     44  farzeen      m     manager      88
2     55    gavin      m      waiter      88
3     56    nasir      m        boss      99
4     77   shahim      m    watchman      99
5     89    moosa      m         ceo      99
   empid     name gender designation  salary
1     22    mugni      g      worker      50
2     44  farzeen      m     manager      88
3     55    gavin      m      waiter      88
4     56    nasir      m        boss      99
5     77   shahim      m    watchman      99
6     89    moosa      m         ceo      99
   empid   name gender designation  salary
0     22  mugni      g      worker      50
   empid   name gender designation  salary
0     22  mugni      g      worker      50
   empid     name gender designation  salary
1     44  farzeen      m     manager      88
2     55    gavin      m      waiter      88
3     56    nasir      m        boss      99
4     77   shahim      m    watchman      99
5     89    moosa      m         ceo      99
   empid   name gender designation  salary
0     22  mugni      g      worker      50
   empid   name gender designation  salary
0     22  mugni      g      worker      50

In [2]:
#task 1
import numpy as np
import pandas as pd
data=[10,np.nan,25,30,np.nan,45,50,np.nan,60]
a=pd.Series(data)
print(a)
print(a.isnull().sum())
print(a.dropna())

0    10.0
1     NaN
2    25.0
3    30.0
4     NaN
5    45.0
6    50.0
7     NaN
8    60.0
dtype: float64
3
0    10.0
2    25.0
3    30.0
5    45.0
6    50.0
8    60.0
dtype: float64

In [15]:
print(a.dropna(inplace=True))
print(pd.Series(a))

None
0    10.0
2    25.0
3    30.0
5    45.0
6    50.0
8    60.0
dtype: float64

In [58]:
#task 2
data={"product":["bat","ball","wicket","football","gloves"],
      "price":[40,50,60,70,80],
      "quantity":[3,4,5,6,7],
      "year":[2024,2025,2026,2022,2021]}
print(data)
df=pd.DataFrame(data)
print(df)
print(df["product"])
print(df[["product","price"]])
print(df.iloc[0,0])
print(df.iloc[0:2,0:3])
print(df.loc[2,"price"])
print(df.loc[[1,3],["product","year"]])

{'product': ['bat', 'ball', 'wicket', 'football', 'gloves'], 'price': [40, 50, 60, 70, 80], 'quantity': [3, 4, 5, 6, 7], 'year': [2024, 2025, 2026, 2022, 2021]}
    product  price  quantity  year
0       bat     40         3  2024
1      ball     50         4  2025
2    wicket     60         5  2026
3  football     70         6  2022
4    gloves     80         7  2021
0         bat
1        ball
2      wicket
3    football
4      gloves
Name: product, dtype: object
    product  price
0       bat     40
1      ball     50
2    wicket     60
3  football     70
4    gloves     80
bat
  product  price  quantity
0     bat     40         3
1    ball     50         4
60
    product  year
1      ball  2025
3  football  2022

In [85]:
#task 3
states={'state':['karnataka','kerala','tamilnadu','goa'],
        'pop':[6.5,3.8,7.2,1.5],
        'area':[191791,38863,130058,3702]}
df=pd.DataFrame(states)
print(df)
df1=pd.DataFrame(states,index=[101,102,103,104])
print(df1)
print(df1.loc[103])
print(df1.loc[:,'pop'])
print(df1.loc[102:])
print(df1.loc[[102,104],['state','area']])

       state  pop    area
0  karnataka  6.5  191791
1     kerala  3.8   38863
2  tamilnadu  7.2  130058
3        goa  1.5    3702
         state  pop    area
101  karnataka  6.5  191791
102     kerala  3.8   38863
103  tamilnadu  7.2  130058
104        goa  1.5    3702
state    tamilnadu
pop            7.2
area        130058
Name: 103, dtype: object
101    6.5
102    3.8
103    7.2
104    1.5
Name: pop, dtype: float64
         state  pop    area
102     kerala  3.8   38863
103  tamilnadu  7.2  130058
104        goa  1.5    3702
      state   area
102  kerala  38863
104     goa   3702

In [7]:
#task 4
data = { 
    "roll_no": [1,2,3,4,5,6,7,8], 
    "name": ["Amit","Neha","Rahul","Sneha","Vikram","Anjali","Kiran","Pooja"], 
    "gender": ["M","F","M","F","M","F","M","F"], 
    "marks": [78, 85, 67, 92, 45, 88, 55, 73], 
    "grade": ["B","A","C","A","D","B","C","B"] 
} 
a=pd.DataFrame(data)
print(a)
print(a[a["marks"]>80])
print(a[(a["marks"]>80)|(a["gender"]=="f")])
print(a[(a["marks"]<60)|(a["gender"]=="m")])
print(a.loc[(a["marks"]>60)&(a["marks"]<90),["name","grade"]])
print(a[(["grade"]=="A")|(a["marks"]>90)])

   roll_no    name gender  marks grade
0        1    Amit      M     78     B
1        2    Neha      F     85     A
2        3   Rahul      M     67     C
3        4   Sneha      F     92     A
4        5  Vikram      M     45     D
5        6  Anjali      F     88     B
6        7   Kiran      M     55     C
7        8   Pooja      F     73     B
   roll_no    name gender  marks grade
1        2    Neha      F     85     A
3        4   Sneha      F     92     A
5        6  Anjali      F     88     B
   roll_no    name gender  marks grade
1        2    Neha      F     85     A
3        4   Sneha      F     92     A
5        6  Anjali      F     88     B
   roll_no    name gender  marks grade
4        5  Vikram      M     45     D
6        7   Kiran      M     55     C
     name grade
0    Amit     B
1    Neha     A
2   Rahul     C
5  Anjali     B
7   Pooja     B
   roll_no   name gender  marks grade
3        4  Sneha      F     92     A

In [31]:
#data cleaning-handling null values in to dataframe
dict={"state":["kar",np.nan,"kar",np.nan],
      "year":[2022,2023,2024,2025],
      "pop":[1,2,3,4]}
df=pd.DataFrame(dict,columns=["state","year","pop","debt"])
print(df)

  state  year  pop debt
0   kar  2022    1  NaN
1   NaN  2023    2  NaN
2   kar  2024    3  NaN
3   NaN  2025    4  NaN

In [33]:
#checking for null values
print(df.isnull().sum())
print(df.isna().sum())

state    2
year     0
pop      0
debt     4
dtype: int64
state    2
year     0
pop      0
debt     4
dtype: int64

In [39]:
#droping null values in data frame
print(df.dropna())

#axis-0-row wise default
#axis-1-column wise deletion
print(df.dropna(axis=0))
print(df.dropna(axis=1,inplace=True))
print(df)

Empty DataFrame
Columns: [state, year, pop, debt]
Index: []
Empty DataFrame
Columns: [state, year, pop, debt]
Index: []
None
   year  pop
0  2022    1
1  2023    2
2  2024    3
3  2025    4

In [38]:
#checking and filling null values
dict={"subjects":["pysics","chem","maths","eng"],
      "s1":[30,np.nan,66,55],
      "s2":[31,66,np.nan,55],
      "s3":[32,77,44,np.nan],
      "s4":[33,42,21,np.nan]}
print(dict)      
df=pd.DataFrame(dict)
print(df)
print(df.isnull().sum())

{'subjects': ['pysics', 'chem', 'maths', 'eng'], 's1': [30, nan, 66, 55], 's2': [31, 66, nan, 55], 's3': [32, 77, 44, nan], 's4': [33, 42, 21, nan]}
  subjects    s1    s2    s3    s4
0   pysics  30.0  31.0  32.0  33.0
1     chem   NaN  66.0  77.0  42.0
2    maths  66.0   NaN  44.0  21.0
3      eng  55.0  55.0   NaN   NaN
subjects    0
s1          1
s2          1
s3          1
s4          1
dtype: int64

In [39]:
#fillna()
print(df.fillna(df))

  subjects    s1    s2    s3    s4
0   pysics  30.0  31.0  32.0  33.0
1     chem   NaN  66.0  77.0  42.0
2    maths  66.0   NaN  44.0  21.0
3      eng  55.0  55.0   NaN   NaN

In [50]:
#ffil()
print(df.ffill())

  subjects    s1    s2    s3    s4
0   pysics  30.0  31.0  32.0  33.0
1     chem  30.0  66.0  77.0  42.0
2    maths  66.0  66.0  44.0  21.0
3      eng  55.0  55.0  44.0  21.0

In [52]:
#bfill()
print(df.bfill())

  subjects    s1    s2    s3    s4
0   pysics  30.0  31.0  32.0  33.0
1     chem  66.0  66.0  77.0  42.0
2    maths  66.0  55.0  44.0  21.0
3      eng  55.0  55.0   NaN   NaN

In [62]:
#mean
a=df["s1"].mean()
print(a)
print(df["s1"].fillna(a,inplace=True))
print(df)

50.333333333333336
None
  subjects         s1    s2    s3    s4
0   pysics  30.000000  31.0  32.0  33.0
1     chem  50.333333  66.0  77.0  42.0
2    maths  66.000000   NaN  44.0  21.0
3      eng  55.000000  55.0   NaN   NaN

In [69]:
#mode
a=df["s2"].mode()
print(a)
print(df["s2"].fillna(a,inplace=True))
print(df)

0    55.0
Name: s2, dtype: float64
None
  subjects         s1    s2    s3    s4
0   pysics  30.000000  31.0  32.0  33.0
1     chem  50.333333  66.0  77.0  42.0
2    maths  66.000000  55.0  44.0  21.0
3      eng  55.000000  55.0  44.0   NaN

In [66]:
#median
a=df["s3"].median()
print(a)
print(df["s3"].fillna(a,inplace=True))
print(df)

44.0
None
  subjects         s1    s2    s3    s4
0   pysics  30.000000  31.0  32.0  33.0
1     chem  50.333333  66.0  77.0  42.0
2    maths  66.000000  55.0  44.0  21.0
3      eng  55.000000  55.0  44.0   NaN

In [70]:
#mean
a=df["s4"].mean()
print(a)
print(df["s4"].fillna(a,inplace=True))
print(df)

32.0
None
  subjects         s1    s2    s3    s4
0   pysics  30.000000  31.0  32.0  33.0
1     chem  50.333333  66.0  77.0  42.0
2    maths  66.000000  55.0  44.0  21.0
3      eng  55.000000  55.0  44.0  32.0

In [75]:
#sorting method
print(df["s4"].sort_values()) #by default ascending order
print(df["s4"].sort_values(ascending=False))#descending order

2    21.0
3    32.0
0    33.0
1    42.0
Name: s4, dtype: float64
1    42.0
0    33.0
3    32.0
2    21.0
Name: s4, dtype: float64

In [79]:
#merging of two data frames
students=pd.DataFrame({"id":[3,4,5],
                       "name":["a","b","c"],
                      })
marks=pd.DataFrame({"id":[3,4,5],
                      "marks":[22,23,24]
                     })
pd.merge(students,marks,on="id")

   id name  marks
0   3    a     22
1   4    b     23
2   5    c     24

In [16]:
#task 1
import numpy as np
data = { 
"City": ["Delhi", "Mumbai", np.nan, "Chennai"], 
"Popula on": [19, 20, 15, np.nan], 
"Area": [1484, np.nan, 426, 1189] 
} 
df=pd.DataFrame(data)
print(df)
print(df.isna().sum())
print(df.dropna(axis=0))
print(df.dropna(axis=1))
print(df.dropna(axis=1,inplace=True))
print(df)

      City  Popula on    Area
0    Delhi       19.0  1484.0
1   Mumbai       20.0     NaN
2      NaN       15.0   426.0
3  Chennai        NaN  1189.0
City         1
Popula on    1
Area         1
dtype: int64
    City  Popula on    Area
0  Delhi       19.0  1484.0
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]
None
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [49]:
#task 2
data = { 
"City": ["Delhi", "Mumbai", np.nan, "Chennai"], 
"Population": [19, 20, 15, np.nan], 
"Area": [1484, np.nan, 426, 1189] 
} 
df=pd.DataFrame(data)
print(df.fillna(0))
print(df.ffill())
print(df.bfill())
b=df["Population"].mean()
print(df["Population"].fillna(b,inplace=True))
c=df["Area"].median()
print(df["Area"].fillna(c,inplace=True))
print(df)

      City  Population    Area
0    Delhi        19.0  1484.0
1   Mumbai        20.0     0.0
2        0        15.0   426.0
3  Chennai         0.0  1189.0
      City  Population    Area
0    Delhi        19.0  1484.0
1   Mumbai        20.0  1484.0
2   Mumbai        15.0   426.0
3  Chennai        15.0  1189.0
      City  Population    Area
0    Delhi        19.0  1484.0
1   Mumbai        20.0   426.0
2  Chennai        15.0   426.0
3  Chennai         NaN  1189.0
None
None
      City  Population    Area
0    Delhi        19.0  1484.0
1   Mumbai        20.0  1189.0
2      NaN        15.0   426.0
3  Chennai        18.0  1189.0

In [54]:
#task 3
students = { 
"ID": [1,2,3,4,5], 
"Name": ["Amit","Riya","Karan","Sneha","Vikram"], 
"Marks": [78, 92, 67, 85, 74] 
} 
a=pd.DataFrame(students)
print(a)
print(a["Marks"].sort_values())
print(a["Marks"].sort_values(ascending=False))

   ID    Name  Marks
0   1    Amit     78
1   2    Riya     92
2   3   Karan     67
3   4   Sneha     85
4   5  Vikram     74
2    67
4    74
0    78
3    85
1    92
Name: Marks, dtype: int64
1    92
3    85
0    78
4    74
2    67
Name: Marks, dtype: int64

In [85]:
emp = { 
"ID": [101,102,103,104], 
"Name": ["John","Priya","Arun","Megha"] 
} 
salary = {
    "ID": [101,102,103,104], 
"Salary": [20000,25000,30000,27000] 
} 
a=pd.DataFrame(emp)
b=pd.DataFrame(salary)
print(a)
print(b)
c=pd.merge(a,b,on="ID")
print(c)
print(c[["Name","Salary"]])
print(c["Salary"].sort_values(ascending=False))

    ID   Name
0  101   John
1  102  Priya
2  103   Arun
3  104  Megha
    ID  Salary
0  101   20000
1  102   25000
2  103   30000
3  104   27000
    ID   Name  Salary
0  101   John   20000
1  102  Priya   25000
2  103   Arun   30000
3  104  Megha   27000
    Name  Salary
0   John   20000
1  Priya   25000
2   Arun   30000
3  Megha   27000
2    30000
3    27000
1    25000
0    20000
Name: Salary, dtype: int64